### ISSUE TITLE
MACOSX (zsh) does not recognize square brackets [ ]

### ISSUE THREAD

**Issue by FreekvanLeijen** [MotionbyLearning/PyDePSI#18]
While following the installation instructions, I ran into this error on my MacBook:

% pip install -e .[dev,docs]
zsh: no matches found: .[dev,docs]

What works:
```
pip install -e . \[dev,docs\]
```
Please have a look.

**Comment by rogerkuou** [comment]
I found someone has the same issue [here](https://github.com/mu-editor/mu/issues/852) with `zsh` and [here](https://stackoverflow.com/questions/30539798/zsh-no-matches-found-requestssecurity/30539963).
It seems `zsh` uses [square brackets for globbing / pattern matching](http://zsh.sourceforge.net/Guide/zshguide05.html#l137).

I will update the doc to implement the suggestion made in one of the above issues:

```sh
pip install -e ".[dev,docs]"
```

This works for me and seems works universally.
